name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.5
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.4.2
  dcli: ^3.0.2
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: d960c0bdc6dc553eaa75d5ddddb34cab530578b8

dev_dependencies:
  test: ^1.24.4
  lints: ^2.1.1
