name: znn_cli_dart
description: Zenon CLI tool
version: 0.0.5
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  args: ^2.4.2
  dcli: ^3.0.2
  znn_sdk_dart:
    path:
      ../znn_sdk_dart
    #git:
    #  url: https://github.com/hypercore-one/znn_sdk_dart.git
    #  ref: feature/bigint

dev_dependencies:
  test: ^1.17.9
  lints: ^1.0.1
